name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.0
  pdf: ^3.11.0
  printing: ^5.13.0
  fl_chart: ^0.70.0
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  excel: ^4.0.3
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.7

dependency_overrides:
  image: ^4.1.0
